### ISSUE TITLE
`seq_reset` for resetting round-robin counter

### ISSUE THREAD

**Issue by kinwie** [sfz/opcode-suggestions#15]
It will be a useful function if the `seq_` counter can be reset by user. So, maybe adding a new opcode like `seq_reset`=N can solved the need. `N` is the key number, so user can press the defined key to reset the counter and start from 1 again.
Practically useful for Strings Up-Down bowing or Guitar Down-Up picking, etc...

**Comment by DSmolken** [comment]
Potentially this kind of thing is also very useful for choirs, where each round robin in the sequence could be a different syllable.

**Comment by jlearman** [comment]
Mightt it be better to use a controller?  If it's reset on a note, call it seq_reset_key=N or seq_reset_note=N.  Or seq_reset_keyN=0 where N is the note and 0 (or whatever) is the RR sequence number.  If you might need to start at the top, you also might need to start elsewhere.  With a CC, the CC value could select the index.  (seq_setcc=N)

**Comment by kinwie** [comment]
Well yeah, to be able using a CC is a good and flexible solution. And also correct, as one phrase can start with a up-picking or up-bowing, so to be able to choose the position is better.
Maybe like the `amp_velcurve_N`=X opcode, this also can have similar name like `seq_reset_N`=X, where X is the position number and N is the key/note number, or vice versa.
While for CC, maybe like `seq_reset_onccN`=X
Anyway, the basic idea is to be able to control the starting point of the RR

**Comment by DSmolken** [comment]
Yes, it would also be good to be able to jump to a specific point in a sequence of RRs, for choir purposes, or being able to start a phrase with either an up or down bow.

This would require a major reorganization of how RRs work, though, because at least in ARIA RRs are within-region. For alternating bowing, legato also becomes important, and we'd need a global RR counter, not a region one, and this easily turns into a rabbit hole of "oh, and I can think of one more feature I'd want with that" like not changing bow direction with every note, but only with every trigger=first note...
