### ISSUE TITLE
Replacement opcodes for extended CCs

### ISSUE THREAD

**Issue by MTornPDX** [sfz/opcode-suggestions#28]
Should we consider a way to phrase extended CCs in a more intuitive way?
For example, I use cc131 (velocity), cc133 (note number), cc135 and cc136 (random) A LOT. And if my keyboard had aftertouch I'd use cc129 a lot too.

These numbers are quite secret and unintuitive, in fact I didn't discover them for quite a while. And I still have to look them up often to remind myself what number does what.
Shouldn't we be able to write things like cutoff_onvel or offset_onunirand, or perhaps amplfo_depth_onkey (or perhaps it should be _onnn)?

A few of the ccs above 137 are useful too (others are just a bit weird) - I like cc140 (key delta) and cc153 (number of keys held down).

**Comment by paulfd** [comment]
As an solution in the meantime you can define constants, e.g. ```#define $velocity 131… cutoff_on$velocity=…``` I am on a phone so I didn’t test but it should work! From: MTornPDXSent: Sunday, August 8, 2021 5:32 PMTo: sfz/opcode-suggestionsCc: SubscribedSubject: [sfz/opcode-suggestions] Replacement opcodes for extended CCs (#28) 
Should we consider a way to phrase extended CCs in a more intuitive way?
For example, I use cc131 (velocity), cc133 (note number), cc135 and cc136 (random) A LOT. And if my keyboard had aftertouch I'd use cc129 a lot too.
These numbers are quite secret and unintuitive, in fact I didn't discover them for quite a while. And I still have to look them up often to remind myself what number does what.
Shouldn't we be able to write things like cutoff_onvel or offset_onunirand, or perhaps amplfo_depth_onkey (or perhaps it should be _onnn)?
A few of the ccs above 137 are useful too (others are just a bit weird) - I like cc140 (key delta) and cc153 (number of keys held down).

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/sfz/opcode-suggestions/issues/28",
"url": "https://github.com/sfz/opcode-suggestions/issues/28",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by paulfd** [comment]
As a solution in the meantime you can define constants, e.g.

```
#define $velocity 131
… cutoff_on$velocity=…
```

I am on a phone so I didn’t test but it should work!

**Comment by MTornPDX** [comment]
Al

> As a solution in the meantime you can define constants, e.g.
> 
> ```
> #define $velocity 131
> … cutoff_on$velocity=…
> ```
> 
> I am on a phone so I didn’t test but it should work!

Almost! It works with

```
#define $velocity cc131
```

I've never played with Define, it might be pretty useful.
Of course, you still need to either memorize the secret ccs, or look them up.

**Comment by DSmolken** [comment]
Would definitely be a good idea, especially when it comes to adding even more extended parameters.
