### ISSUE TITLE
use of percentages in the "offset" opcode

### ISSUE THREAD

**Issue by michael02022** [sfz/opcode-suggestions#30]
instead of an exact number, you can use a percentage from 0 to 100, where depending of the percentage result, that gonna be the section that will be skipped in the sample 
if you write "offset=2%", it will calculate the result based on the sample size for each one
sample-size | result of 2%
sample 1: 35654 -> 713
sample 2: 75456 -> 1509
sample 3: 48289 -> 965
also you can use decimals like 1.5%
for precision
not sure if it can be done with the same opcode or should be a new opcode for that like offset%=2.1

**Comment by MTornPDX** [comment]
The current way of measuring offsets is pretty awkward. Should you really need to keep the sample rate in mind when setting an offset?
But rather than a percentage, which instead requires you to know how long your raw samples are, how about simply defining offset in seconds? After all, that's how we do almost everything else, like envelope times, delay, etc.

**Comment by plgDavid** [comment]
Some ARIA Extension SFZs in the field already have been using a variant of this idea (since 2021 ish)
EG:
offset_mode=percent //switches the offset opcode from its default "offset_mode=samples" behaviour
offset_oncc257=50 //random offset from 0 to half the file

This is included in sforzando since v1.971
