### ISSUE TITLE
Legato counter

### ISSUE THREAD

**Issue by jpcima** [sfz/opcode-suggestions#4]
**Description**

The request to select regions on the basis of a legato counter.

The regions may be associated with legato numbers which selects them.
It's also suggested that a modulo counter can be used, so it wraps back to the first when it reaches the end.

The name `legato_trigger` was suggested.
It's not sure if trigger is appropriate term to use for this context.

If a modulo counter is desired, one could set some opcode `legato_counter=N`, and then the legato will be counted 1 to N and wrap. Without a counter, it counts to infinity.

---

A region might be described as something like:
```
<region>
legato_trigger=1
```

Or possibly in a range fashion, like some existing selection opcodes
```
<region>
lolegato_trigger=1
hilegato_trigger=5
```

The `legato_trigger` would set both lo and hi.
If either lo or hi is not set, the undefined bound may be taken to be 1 or infinity, for lo and hi respectively.

---

There is also a wish to allow a keyswitch to reset the legato counter to a desired value, in particular the value 1.

**Comment by AlexMitchellMus** [comment]
Currently in SFZ there is already 
```
seq_length=N 
seq_position=N
```
Which allows round robins.
Something similar for a legato counter would be useful for monophonic instruments, with advanced phrasing needs, like strings, vocals, etc.

So instead of my suggested Opcodes above, use:
```
legato_seq_length=N
legato_seq_position=N
```
Both could be per region, as legato_seq_length is taking the modulo of the master legato count.

As pointed out above, there would also need to be a switch opcode to be able to reset the counter to a value, this opcode would need to be global, as legato counting happens at an instrument level (example only):
```
<global>
sw_legato_value <seq value> = <key>
```
