### ISSUE TITLE
Add more headers

### ISSUE THREAD

**Issue by kinwie** [sfz/opcode-suggestions#9]
As the `<master>` already added by ARIA, it is very helpful. But we need more headers below `<global>`

**Comment by redtide** [comment]
I believe that adding headers in the current way will only make the situation worse because is not scalar, it looks like to me a way to create hierarchies in a linear way instead a recursive one.
E.g. instead some 
```
<global>
<master>
<group>
```
have some
```
<global>
    <sub>
        <sub>
```
tree like hierarchy (the second sub is not at the same level of the previous, unlike `<group>` and family works.

**Comment by jlearman** [comment]
I agree with @redtide .  A nesting solution is far better.  If we had that, we'd stop using most of the others.  The one benefit the others have is the label, which is useful for debugging purposes.  For the <sub> header, we could have a sub_label opcode, and all sub labels could be concatenated with ":" separators, to produce one label line for all sub sections.

**Comment by paulfd** [comment]
I do agree too, and the changes I'm pushing in allow this change down the line. The issue as I understand it is that in the current sfz grammar, there is no closing tags (like XML) or semantics for tabs or whitespace. So for the 
```
<global>
    <sub>
        <sub>
```
example, there is no way to know if the second `sub` is a child of the first `sub` or a child the `global`. If we used a true XML grammar for example this would be built-in. The named levels are necessary to avoid this ambiguity in the current grammar.

**Comment by redtide** [comment]
I recall in some code generator there was a tracked indentation, so it might be some "header attribute" that specify the nesting level?

**Comment by jlearman** [comment]
Good point paulfd.  I suggest \<endsub\> or \<sub_end\>, and issue an error if there is a sub without an end.  That way people will tend to close the bracket.  And no big parser changes.

**Comment by AlexMitchellMus** [comment]
René intentionally didn't go down the path of XML. I'm not saying this is a bad idea, but I think for SFZ format itself its important to keep the syntax similar?

I do like the idea of indenting however. Could this not be achieved if SFZ file format understood `new line` and `spaces` alone?

**Comment by redtide** [comment]
@alcomposer is right; having something like what I proposed is already something that goes a bit too much beyond the format nature, having closing tags will completely change it. OTOH adding some kind of attribute will add complexity that was avoided from the beginning, so no idea how to solve this in a proper manner.
What I mean with attributes would be something like:
```
<global>
    <sub level=1 label="Pseudo master">
        <sub level=2 label="A group">
    <sub level=1 label="Another master">
        <sub level=2 label="Another group on 2nd master">
            <sub level=3 label="A sub group">
```
(indentation would be optional, just to point out the logic)

**Comment by kinwie** [comment]
Yeah, I'm thinking simple one like @alcomposer said. Like adding 2 more, but still hierarchy, e.g :
`<global>`
`<master>`
`<main>`
`<sub>`
`<group>`
`<region>`

**Comment by AlexMitchellMus** [comment]
I really like the idea of additional headers. But like Python got rid of `{}` to signify a block of code, I feel SFZ Format _could_ do the same thing.

Alchemy (native file format) already has such indenting, and having looked at the files, it does make it easier to read- and faster to write.

I also feel that it moves in the direction set out for SFZ- without **just do XML** ™

**Comment by paulfd** [comment]
@alcomposer Was/is there a very strong argument against XML? I'm not an XML fan by any stretch of the imagination, but the problem we see popping there is a solved one for general purpose markup languages and semi-structured data formats. With XML and many others you also get tooling to:
- Specify your schema (DTD) and validate files against this schema
- Specify versions of the schema (the tag on top of XML-compliant files)
- Rely on existing libraries for the parsing
- Have general purpose editors and analyzers
- Query the data (XQL)
- Provide semi-automatic upgrading of files from one schema to the next (XSLT)
- ...

---

Onto the subject at hand: if you use indentation to carry scoping information, my bet is that you will break many current sfz libraries, plus the fact that the general public does not think of whitespace as having meaning---I like the terseness of Python, but believe me when I say that's it's a nightmare to teach at first.

My initial goal with the implementation was that it's technically useless to limit the logic to 4 levels, and this opens an easier transition path down the line, _mostly for another front-end language other than the original sfz syntax_. 

I'm more a developer than a user, and my opinion is as follows:
- @kinwie 's approach with additional headers is straightforward, although maybe a bit verbose in the code. Probably the easiest for people to grasp though considering it aligns with the current principes of SFZ.
- @redtide 's idea with the `level=` opcode is a bit annoying to parse because you need to wait until you read the members (opcodes) of the level to know if it's a child or sibling, but that's more of a developer issue so it's not a big problem. What I fear is that it makes a file harder to read and reason about maybe (for humans, not computers)?
- Indentation or closing blocks are deep changes to the SFZ grammar. My opinion is that if we decide to go there we might as well argue that a proper markup language is the right answer.

**Comment by jlearman** [comment]
I think that indentation is a bad idea, as is level=, because these do not allow inclusion of multiple instruments into one sfz.  Furthermore, with indentation, you have to worry about conversion between tabs and spaces, which was a bit of a nightmare for Python.

I don't think that a closing opcode is a change to the grammar, only to the semantics.  Just as many opcodes set a state variable, opcodes that open and close a block could modify a state variable, pushing/popping a context identifier.  The parser per se doesn't change; only the opcode implementation changes.  Of course, this affects all the opcode implementations by adding an additional context variable. 

IMHO a trickier part would be figuring out how to manage other headers inside a \<sub\>.  I suggest that \<sub\> be higher in precedence to \<region\> and \<group\> and lower than \<global\> and \<master\> (and hopefully we'd stop using those two in favor of \<sub>\.)  The trickiest part might be figuring out how to handle \<control\> headers inside \<sub\>.
